# Site settings
title: Navi's Linux Gaming Hub
email: naviabbot@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Install Guides and Gaming Vids
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
